swagger: "2.0"

info:
  title: "Aggregator"
  version: "1.0"

basePath: /1.0

paths:
  /trade:
    post:
      tags: [Post Trade]
      operationId: api.trade.collect
      produces:
          - "application/json"
      parameters:
        - name: "trade stream"
          in: "body"
          description: "trade stream"
          required: true
          schema:
            $ref: "#/definitions/trade_stream"
      responses:
        200:
          description: "success data stream"
          schema:
            type: string
        default:
          description: "error"
          schema:
            type: string

definitions:
  trade_stream:
    type: object
    properties:
      symbol:
        type: string
      hour:
        type: integer
      minute:
        type: integer
      seconds:
        type: integer
      milliseconds:
        type: integer
      price:
        type: number
        format: float
      lastSize:
        type: number
        format: float
