swagger: "2.0"

info:
  title: "Aggregator"
  version: "1.0"

basePath: /1.0

paths:
  /trade:
    post:
      tags: [Post Trade]
      operationId: api.trade.collect
      produces:
          - "application/json"
      parameters:
        - name: "trade stream"
          in: "body"
          description: "trade stream"
          required: true
          schema:
            $ref: "#/definitions/trade_stream"
      responses:
        200:
          description: "success data stream"
          schema:
            type: string
        default:
          description: "error"
          schema:
            type: string

definitions:
  trade_stream:
    type: object
    properties:
      symbol:
        type: string
      year:
        type: integer
      month:
        type: integer
      day:
        type: integer
      hour:
        type: integer
      minute:
        type: integer
      seconds:
        type: integer
      milliseconds:
        type: integer
      timestamp:
        type: string
        format: date-time
      price:
        type: number
        format: float
      price_precision:
        type: integer
      last_size:
        type: number
        format: float
    example: {
          "symbol": "AAPL",
          "year": 2016,
          "month": 12,
          "day": 22,
          "hour": 12,
          "minute": 0,
          "seconds": 0,
          "milliseconds": 0,
          "timestamp": "2016-12-22T12:00:00Z",
          "price": 123.4567,
          "price_precision": 2,
          "last_size": 2000
        }

