version: '2'
services:
  database:
    restart: always
    image: mysql
    ports:
      - "7603:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpass'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'collector'

  collector:
    restart: always
    build: .
    ports:
      - "18081:8080"
    links:
      - database
    depends_on:
      - database
    environment:
      UWSGI_PORT: 8080
    tty: true
