version: '2'
services:
  database:
    restart: always
    image: mysql
    ports:
      - "6603:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpass'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'collector'

  collector:
    restart: always
    build: .
    ports:
      - "18080:8080"
    links:
      - database
    environment:
      UWSGI_PORT: 8080
    tty: true