"""empty message

Revision ID: 04a9da19539d
Revises: d2895554e7a9
Create Date: 2016-12-22 16:11:12.638617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04a9da19539d'
down_revision = 'd2895554e7a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stream_trade', sa.Column('day', sa.Integer(), nullable=False))
    op.add_column('stream_trade', sa.Column('month', sa.Integer(), nullable=False))
    op.add_column('stream_trade', sa.Column('price_precision', sa.Integer(), nullable=False))
    op.add_column('stream_trade', sa.Column('year', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stream_trade', 'year')
    op.drop_column('stream_trade', 'price_precision')
    op.drop_column('stream_trade', 'month')
    op.drop_column('stream_trade', 'day')
    # ### end Alembic commands ###
